### ISSUE TITLE
Evaluate Jenkins pipelines to model release process

### ISSUE THREAD

**Issue by grebaldi** [neos/release-process#21]
Documentation on pipelines:

- https://jenkins.io/doc/book/pipeline/
- https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md

The "Blue Ocean" project:

- https://jenkins.io/projects/blueocean/
https://jenkins.io/doc/book/blueocean/creating-pipelines/

**Comment by kdambekalns** [comment]
Having read documentation and played around with the pipelines DSL I think we can build what we need with it:

- steps can be defined as needed using Groovy
- existing jobs can be called as part of a pipeline
- waiting (indefinitely) for a step to complete is possible
